### PR TITLE
Specializing Functional  Interfaces

### PR DESCRIPTION
**Pull request by ameyaKetkar**
Some results from the tool.

### CODE REVIEW

**Comment by minborg** [comment]
Thank you for fixing this. I will approve the pull request once you have signed the Contributor License Agreement at https://www.clahub.com/agreements/speedment/speedment

**Comment by ameyaKetkar** [comment]
Thank you. 
Well! this link shows that i have already signed the CLA. :)

**Comment by minborg** [comment]
Ooops. My bad. Thank you for this PR!

**Comment by ameyaKetkar** [comment]
Thanks

**Pull request merged**
