### PR TITLE
clearTables mojo

### PR DESCRIPTION
**Pull request by ractoc**
Added a new mojo to the maven plugin, clearTables. This mojo will remove all tables from all schemas in all dbmses in the speedment.json configuration file. This way, it becomes possible to clean up tables no longer present in the database.

### CODE REVIEW

**Comment by minborg** [comment]
Great news. Before I can accept the pull request, you need to sign the contributor license as described here:

https://github.com/speedment/speedment/blob/master/CONTRIBUTING.md

This will protect your work and also make sure we can use your code in the open-source project.

**Comment by ractoc** [comment]
Thuis is nooit my forte contribution, so there should be one of those from me already.

⁣Verzonden door BlueMail ​

Op 29 aug. 2017 08:35, om 08:35, "Per-Åke Minborg" <notifications@github.com> schreef:

**Comment by minborg** [comment]
I remember that but I cannot find "ractoc" in the list of people who signed. Did you sign under another alias? I am confused...

**Comment by ractoc** [comment]
Maybe Mark Schrijver?

⁣Verzonden door BlueMail ​

Op 29 aug. 2017 08:35, om 08:35, "Per-Åke Minborg" <notifications@github.com> schreef:

**Comment by minborg** [comment]
I have carefully reviewed the list of signers and your name is not on the list. Would it be possible for you to sign? We have no person signed form the Netherlands or no one with your alias or name.

**Pull request merged**
