### PR TITLE
Add some useful badges with automatic version detection: Maven and Javadoc

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by valery1707** [comment]
CLA now is signed

**Comment by anton-johansson** [comment]
Looks good to me! Maybe should be merged to ```develop``` instead for easier merging in the future? After all, ```develop``` is 375 commits ahead. :)

**Comment by valery1707** [comment]
I create separate PR #150, this one can be closed

**Comment by Pyknic** [comment]
Nice badges! I have merged the other PR.

**Comment by valery1707** [comment]
Thanks!

**Pull request closed without merging**
